/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppbarComponent: typeof import('./src/components/AppbarComponent.vue')['default']
    AppBodyComponent: typeof import('./src/components/AppBodyComponent.vue')['default']
    FIltersSectionComponent: typeof import('./src/components/FIltersSectionComponent.vue')['default']
    TaskListComponent: typeof import('./src/components/TaskListComponent.vue')['default']
    TaskSectionToggleComponent: typeof import('./src/components/TaskSectionToggleComponent.vue')['default']
    TasksStatusComponent: typeof import('./src/components/TasksStatusComponent.vue')['default']
  }
}
